### ISSUE TITLE
400 Bad Request (error code: 50006): Cannot send an empty message

### ISSUE THREAD

**Issue by cryptonoise** [Ruu3f/freeGPT-discord#6]
**400 Bad Request (error code: 50006): Cannot send an empty message** - to any message in #freegpt-chat
Everything was fine before, but now this error is constant. Resetting does not help

freegpt [1.2.8]
gpt3

**Comment by Ruu3f** [comment]
GPT-3 is currently broken. I will fix it in the next version of freeGPT.
