### ISSUE TITLE
tls_client is not Defined

### ISSUE THREAD

**Issue by TheBrightSoul** [Ruu3f/freeGPT-discord#8]
Hy there I've managed to make it running on my server and it was running fine from past few months but now there is a error showing that tls_client is not defined when I ask soemthing from it
![image](https://github.com/Ruu3f/freeGPT-discord/assets/90372921/250a5079-6866-4964-aeb2-8eb3699d97a1)

I have tried messing up with code a couple of times but seems like there is no tls_client defined what should i do with it now???
Any help will be greatly appricieated.

and last thing here is a quick summary of whole story in short.
![image](https://github.com/Ruu3f/freeGPT-discord/assets/90372921/e636a3ae-5b67-4362-a979-e7ca7351eff9)

**Comment by Ruu3f** [comment]
It broke because I changed the the way it is accessed.
Check [the examples](https://github.com/Ruu3f/freeGPT) and change your code accordingly
